# Generated by Django 6.1 on 2026-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_reset_frostfire_password'),
        ('schools', '0032_alter_academiccalendar_campus'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False), ('role', 'campus_admin')), fields=('campus', 'role'), name='unique_campus_admin_per_campus'),
        ),
    ]
